version: "3.1"
services:
  app:
    build:
      context: .
      args:
        RAILS_ENV: development
    command: "bundle exec puma"
    user: root
    env_file:
      - docker-compose.env
    volumes:
      - .:/srv/scheduling-dashboard:cached
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    restart: on-failure
    networks:
      - public
networks:
  public:
